import { Inter } from 'next/font/google'
import './globals.css'
import cn from "@/app/(lib)/cn";

const inter = Inter({ subsets: ['latin'] })
//popins
//Avenir
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
      <html lang="en">
        <body className={cn(inter.className)}>
            {children}
        </body>
      </html>
  );
};

export default RootLayout;